### ISSUE TITLE
Console  Continuous output Error

### ISSUE THREAD

**Issue by PorPit** [happyzleaf/PokexpMultiplier#9]
Sponge Version: spongeforge-1.12.2-2655-7.1.0-BETA-3100
pixelmon version: PixelmonGenerations 2.0.3
(http://www.mediafire.com/file/ntcmboy4hgt46ko/PixelmonGenerations-1.12.2-2.0.3-universal.jar)
some time Console  Continuous output Error 
↓

`[13:41:11] [Server thread/ERROR] [FML]: Exception caught during firing event com.pixelmonmod.pixelmon.api.events.ExperienceGainEvent@3bca774f:
java.lang.NullPointerException: null
	at com.github.happyzleaf.pokexpmultiplier.PokexpMultiplier.onExperienceGain(PokexpMultiplier.java:118) ~[PokexpMultiplier.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_140_PokexpMultiplier_onExperienceGain_ExperienceGainEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590) [EventBus.class:?]
	at com.pixelmonmod.pixelmon.entities.pixelmon.stats.Level.awardEXP(Level.java:231) [Level.class:?]
	at com.pixelmonmod.pixelmon.battles.controller.Experience.calcExp(Experience.java:162) [Experience.class:?]
	at com.pixelmonmod.pixelmon.battles.controller.Experience.awardExp(Experience.java:82) [Experience.class:?]
	at com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.catchPokemon(EntityEmptyPokeball.java:389) [EntityEmptyPokeball.class:?]
	at com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.func_70071_h_(EntityEmptyPokeball.java:311) [EntityEmptyPokeball.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:170) [TrackingUtil.class:1.12.2-2655-7.1.0-BETA-3100]
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zll000(WorldServer.java:2881) [oo.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:4151) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6574) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2224) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[13:41:11] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[13:41:11] [Server thread/ERROR] [FML]: 0: NORMAL
[13:41:11] [Server thread/ERROR] [FML]: 1: ASM: com.github.happyzleaf.pokexpmultiplier.PokexpMultiplier@1e069626 onExperienceGain(Lcom/pixelmonmod/pixelmon/api/events/ExperienceGainEvent;)V
[13:41:11] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************/
[13:41:11] [Server thread/ERROR] [Sponge]: /*                                                  Exception occurred during a PhaseState                                                   */
[13:41:11] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************/
[13:41:11] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system makes a best effort to not throw exceptions randomly                                                             */
[13:41:11] [Server thread/ERROR] [Sponge]: /* but sometimes it is inevitable. In most cases, something else triggered this                                                              */
[13:41:11] [Server thread/ERROR] [Sponge]: /* exception and Sponge prevented a crash by catching it. The following stacktrace                                                           */
[13:41:11] [Server thread/ERROR] [Sponge]: /* can be used to help pinpoint the cause.                                                                                                   */
[13:41:11] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************/
[13:41:11] [Server thread/ERROR] [Sponge]: /* The PhaseState having an exception: EntityTickPhase                                                                                       */
[13:41:11] [Server thread/ERROR] [Sponge]: /* The PhaseContext:                                                                                                                         */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     - Owner: EntityPlayerMP['NAOFu_'/14408, l='world', x=-639.83, y=66.00, z=5448.32]                                                     */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     - Source: EntityEmptyPokeball['精灵球'/62102, l='world', x=-650.00, y=64.40, z=5447.00]                                                  */
[13:41:11] [Server thread/ERROR] [Sponge]: /* org.spongepowered.asm.util.PrettyPrinter@3d251885                                                                                         */
[13:41:11] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************/
[13:41:11] [Server thread/ERROR] [Sponge]: /* StackTrace:                                                                                                                               */
[13:41:11] [Server thread/ERROR] [Sponge]: /* java.lang.NullPointerException: null                                                                                                      */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     com.github.happyzleaf.pokexpmultiplier.PokexpMultiplier.onExperienceGain(PokexpMultiplier.java:118)                                   */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler_140_PokexpMultiplier_onExperienceGain_ExperienceGainEvent.invoke(.dynamic) */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)                                            */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652)                                                           */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)                                                           */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.entities.pixelmon.stats.Level.awardEXP(Level.java:231)                                                       */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.battles.controller.Experience.calcExp(Experience.java:162)                                                   */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.battles.controller.Experience.awardExp(Experience.java:82)                                                   */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.catchPokemon(EntityEmptyPokeball.java:389)                            */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.func_70071_h_(EntityEmptyPokeball.java:311)                           */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:170)                                                */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zll000(WorldServer.java:2881)                                             */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72866_a(World.java:4151)                                                                               */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)                                                                    */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72870_g(World.java:1952)                                                                               */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72939_s(World.java:6574)                                                                               */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2224)                                                                   */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)                                                           */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)                                                 */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)                                                           */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)                                                                    */
[13:41:11] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Unknown Source)                                                                                                  */
[13:41:11] [Server thread/ERROR] [Sponge]: /*  Phases Remaining:                                                                                                                        */
[13:41:11] [Server thread/ERROR] [Sponge]: /*                                                                                                                                           */
[13:41:11] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                                        */
[13:41:11] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.1.0-SNAPSHOT-43d8496                                                                                                        */
[13:41:11] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2655-7.1.0-BETA-3100                                                                                                 */
[13:41:11] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.3.2655                                                                                                            */
[13:41:11] [Server thread/ERROR] [Sponge]: /*********************************************************************************************************************************************/
`

**Comment by hqppyz** [comment]
PokexpMultiplier version? Where have you downloaded it?

**Comment by PorPit** [comment]
V1.1.6 from releases webside

Conditions: When player battle with the wild pokemon 
and use pokeball successfull to catch it
player's pokemon will infinite get exp and receive plugin message “XXX's XXX experience has been multiplied from XXX to XXX thanks to his vanilla levels!"”
http://i4.fuimg.com/508137/95f15c591005124d.jpg

**Comment by hqppyz** [comment]
Try this one and tell me if anything changes
https://mega.nz/#!WwRyDaBJ!_JH9uP16VYXrXXYZ9tLpkononMdf493YSngKcl9NPZI

**Comment by PorPit** [comment]
ok

**Comment by PorPit** [comment]
console error log
https://paste.ubuntu.com/p/JQkknwj2jb/

**Comment by hqppyz** [comment]
I'm looking into this asap

**Comment by hqppyz** [comment]
Fixed in 1.1.8
